### ISSUE TITLE
how to use securityContext.readOnlyRootFilesystem=true?

### ISSUE THREAD

**Issue by rgl** [spinkube/containerd-shim-spin#123]
What do we have to do to be able to set `securityContext.readOnlyRootFilesystem=true`?

This is my current `securityContext`, which I would like to not use the parts marked with `TODO`:

```yaml
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              #drop:
              #  - ALL
              # TODO use non-privileged port and drop ALL when the following
              #      issue is resolved.
              #      https://github.com/spinkube/containerd-shim-spin/issues/52
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: false # TODO how to run this with true?
            runAsNonRoot: true
            runAsUser: 65534 # 65534 is the uid of the nobody user.
            runAsGroup: 65534 # 65534 is the gid of the nogroup group.
            seccompProfile:
              type: RuntimeDefault
```
