### ISSUE TITLE
Which `spin up` flags to support in the shim?

### ISSUE THREAD

**Issue by kate-goldenring** [spinkube/containerd-shim-spin#130]
This issue https://github.com/spinkube/containerd-shim-spin/issues/52 starts a conversation about supporting `spin up` flags in the shim. We can ingest these flags from the Container spec `args` array as follows:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin-todo
  template:
    metadata:
      labels:
        app: spin-todo
    spec:
      runtimeClassName: wasmtime-spin-v2
      containers:
      - name: spin-todo
        image: ttl.sh/spin-kv-checklist:48h
        command: ["/"]
        ports:
        - containerPort: 80
        args: ["--key-value", "foo=true"]
```

These args can then be processed from the [`RuntimeContext` passed into `run_trigger`](https://github.com/spinkube/containerd-shim-spin/blob/49d0c57d9533e55950b4007e0043f018a693b19c/containerd-shim-spin/src/engine.rs#L211).

My question is which of the flags we want to support. Some such as `--listen` address are clearly important as noted in https://github.com/spinkube/containerd-shim-spin/issues/52 . The ones that preseed data, `--key-value` and `--sqlite`, could be argued as being uneccessary, especially given that these data sources are likely managed separately of the app lifecycle.
