### ISSUE TITLE
Support application variables in redis trigger configuration

### ISSUE THREAD

**Issue by michelleN** [spinkube/containerd-shim-spin#165]
Spin supports application variables in redis trigger configuration in the spin.toml file: https://github.com/fermyon/spin/blob/286cf439d18b11196cda91278245131f9a62f477/crates/trigger-redis/src/lib.rs#L70-L72

```toml
[application.trigger.redis]
address = "redis://default:{{redis_password}}@{{redis_host}}:13480"
```

I believe the resolving of this section happens here in the Spin codebase: https://github.com/fermyon/spin/blob/main/crates/trigger-redis/src/lib.rs#L70-L72

It'd be nice to support this in the shim as well.
