### ISSUE TITLE
Enable starting only a subset of components

### ISSUE THREAD

**Issue by kate-goldenring** [spinkube/containerd-shim-spin#186]
As a feature request, the shim should be able to execute only a subset of components. This will likely pull in changes from the Spin CLI work around this: https://github.com/fermyon/spin/issues/2820

**Comment by Mossaka** [comment]
Probably want a new [Spin Execution Config](https://github.com/spinkube/skips/blob/main/proposals/003-skips/README.md#spin-application-execution-configuration) variable like `SPIN_COMPONENTS` that takes a list of components. E.g.

```yaml
env:
  - name: SPIN_COMPONENTS
    value: "hello-rust,hello-go"
```
