### ISSUE TITLE
Selective deployment errors not visible in Pod logs

### ISSUE THREAD

**Issue by kate-goldenring** [spinkube/containerd-shim-spin#228]
Say you apply this spin app that has two components `hello` and `goodbye` but select that nonexistent component `foo` is run:
```
apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: hello-salutation-spinapp
spec:
  # TODO: change to image hosted at ghcr.io/spinkube/spin-operator/salutations when published
  image: "ghcr.io/kate-goldenring/spin-operator/examples/spin-salutations:20241022-144454"
  replicas: 1
  executor: containerd-shim-spin
  # Configure the application to only contain the "hello" component
  components: ["foo"]
```
The pod with Error with no logs. You have to look at the containerd logs to find that an improper component was selected:
```
time="2024-11-07T06:09:43.569108376Z" level=error msg="run_wasi ERROR >>>  failed: Specified component "foo" not found in application"

time="2024-11-07T06:09:43.569570479Z" level=info msg="error running start function: Specified component "foo" not found in application"
```

Could we somehow surface this in the Pod logs?
