### ISSUE TITLE
unable to run a pod with two spin apps side-by-side

### ISSUE THREAD

**Issue by rajatjindal** [spinkube/containerd-shim-spin#52]
I was trying out a scenario where two spin apps are running side-by-side in a pod. it seems to fail to start with `address 0.0.0.0:80 is already used` error

pre-requisite: runtime and shim configured. I used following commands:

setting up the cluster
```
k3d cluster create wasm-cluster    \
       --image ghcr.io/spinkube/containerd-shim-spin/k3d:v0.13.1  \
       --port  "8081:80@loadbalancer" \
       --agents 2

kubectl apply -f https://github.com/spinkube/spin-operator/releases/download/v0.1.0/spin-operator.crds.yaml
kubectl apply -f https://github.com/spinkube/spin-operator/releases/download/v0.1.0/spin-operator.runtime-class.yaml
kubectl apply -f https://github.com/spinkube/spin-operator/releases/download/v0.1.0/spin-operator.shim-executor.yaml
```

apply the workload with multiple spin apps

```
kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin-test-multi-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin-test
  template:
    metadata:
      labels:
        app: spin-test
    spec:
      runtimeClassName: wasmtime-spin-v2
      containers:
      - name: spin-test
        image: rajatjindal/http-rust-cooler:v1
        command: ["/"]
        ports:
        - containerPort: 80
      - name: spin-test-service
        image: ghcr.io/spinkube/containerd-shim-spin/examples/spin-rust-hello:v0.13.0
        command: ["/"]
        ports:
        - containerPort: 8080
EOF
```

Error from containerd logs:

```
time="2024-03-27T08:09:37.929901245Z" level=error msg="ERROR >>> Trigger executor failed: Unable to listen on 0.0.0.0:80

Caused by:
    Address in use (os error 98)"
```

It is probably happening because the spin-addr is hardcoded to `0.0.0.0:80` in the shim.
